# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Adrian's Personal Site
description: >- # this means to ignore newlines until "baseurl:"
  Adrian's Personal Site
baseurl: # the subpath of the site
url: "https://adrian-acosta.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
    - name: Projects

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: adrianacosta@ucla.edu
      link: mailto:adrianacosta@ucla.edu
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/the-adrian-acosta
    - name: GitHub
      link: http://github.com/the-adrian-acosta

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
